version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  disable:
    - errcheck
    - revive
    - gosec
    - gocritic
    - bodyclose
    - nilerr
    - prealloc
    - unconvert
    - unparam

linters-settings:
  govet:
    enable:
      - shadow
      - printf
      - nilness

issues:
  exclude-use-default: true
